# Service API Key
api:
  serviceKey: ${API_SERVICE_KEY}

spring:
  application:
    name: trip-plan

  datasource:
    url: jdbc:postgresql://localhost:5432/trip
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect